### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by khalid-hussain** [kanytu/android-material-drawer-template#22]
Hi there,

I'm a beginner at Android development. I can't seem to find an easy way to insert RTL support for the navigation drawer. I've inserted the option `android:supportsRtl="true"` in the manifest and tried [this](http://stackoverflow.com/a/23390446/2002369) but the function no longer accepts integer. I'm not sure how to overcome this.

Will this feature be easy to implement?

**Comment by kanytu** [comment]
I just added `android:supportsRtl="true"` to the manifest and added 

`getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);`

On the activity `onCreate` and I got this result:

![ezgif com-optimize 4](https://cloud.githubusercontent.com/assets/560921/5834012/0986667c-a151-11e4-9893-91e9c1b6185b.gif)

**Comment by khalid-hussain** [comment]
In this case, the `minSdkVersion` has to be 17 right? Or is possible to keep it at its original value?

**Comment by kanytu** [comment]
Yes you're correct. RTL was only added in Android 4.2.

http://developer.android.com/about/versions/jelly-bean.html#42-native-rtl

**Comment by khalid-hussain** [comment]
Thank you very much.
