### ISSUE TITLE
Google Login Window

### ISSUE THREAD

**Issue by sansagara** [kanytu/android-material-drawer-template#24]
How can i implement a google login portion on the drawer like the one in google apps (Gmail, Play Store, etc).  Some like this: http://www.google.com/design/spec/patterns/navigation-drawer.html

Im thinking adding the Google Plus API, but cant find any good tutorial about it.
If you can point me in the right direction, i would thank you.

**Comment by kanytu** [comment]
This is not an issue and has nothing to to with the template. This template enforces developers to implement their own material design application giving them something to start work on.

What you're asking can be simple found by googling a little bit. 
http://bit.ly/1zXcAmI
