### ISSUE TITLE
Do we have to remove ScrimInsetsFrameLayout on Lollipop?

### ISSUE THREAD

**Issue by yolapop** [kanytu/android-material-drawer-template#25]
I just tested my app on Lollipop emulator and somehow when the nav drawer is opened, the scrim is visible on top of the nav drawer. If I remove ScrimInsetsFrameLayout from layout-v21, it works fine..

**Comment by kanytu** [comment]
I think that's the intended effect. Have you looked at Google Play Store? The same bar is visible too. However feel free to remove it from the XML. It will work anyway.

![device-2015-02-09-092212](https://cloud.githubusercontent.com/assets/560921/6103639/57d5ab2a-b03e-11e4-838a-ca1ddf496153.png)
![device-2015-02-09-092606](https://cloud.githubusercontent.com/assets/560921/6103638/57d424bc-b03e-11e4-855d-9aefab5ce80d.png)

**Comment by yolapop** [comment]
No by "on top of the drawer", I meant on the whole screen.. the drawer looked dark when opened (sorry no screenshot available). Maybe that's because the emulator or something but I've removed `ScrimInsetsFrameLayout` and it worked okay.
