### ISSUE TITLE
Accent color not used.

### ISSUE THREAD

**Issue by globus243** [kanytu/android-material-drawer-template#27]
the accent color doesn't show up.
It uses the background color for some reasons

**Comment by globus243** [comment]
also got this. 
getResources().getColor(R.color.myPrimaryDarkColor)); should be getResources().getColor(R.color.myAccentColor));

And in the styles.xml i outcommented these lines:

<item name="android:statusBarColor">@android:color/transparent</item>
<item name="android:windowDrawsSystemBarBackgrounds">true</item>
<item name="android:windowBackground">@color/myWindowBackground</item>

**Comment by kanytu** [comment]
Could you specificity when the accent color is not being used?
