### ISSUE TITLE
setHomeButtonEnabled dosn't work

### ISSUE THREAD

**Issue by bakbuz** [kanytu/android-material-drawer-template#28]
How can I run?

code:
getSupportActionBar().setHomeButtonEnabled(true);
getSupportActionBar().setDisplayHomeAsUpEnabled(true);

**Comment by kanytu** [comment]
When are you calling such methods? And what you're trying to do with them?

**Comment by bakbuz** [comment]
Select one of the items listed to open and display the details so that I want to active the back button on the screen

**Comment by kanytu** [comment]
Then  ` getSupportActionBar().setDisplayHomeAsUpEnabled(true);` will work:


    @Override
    public void onNavigationDrawerItemSelected(int position) {
        Toast.makeText(this, "Menu item selected -> " + position, Toast.LENGTH_SHORT).show();
        if( getSupportActionBar()!=null) {
            getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        }
    }


![image](https://cloud.githubusercontent.com/assets/560921/6349702/fc0460fa-bc24-11e4-94d7-175430813443.png)
