### ISSUE TITLE
fitSystemWindows Overrides a Deprecated Method

### ISSUE THREAD

**Issue by surfer190** [kanytu/android-material-drawer-template#29]
Line 52: ScrimInsetsFrameLayout

Overrides a Deprecated Method

**Comment by kanytu** [comment]
The code was taken from https://github.com/google/iosched/blob/master/android/src/main/java/com/google/samples/apps/iosched/ui/widget/ScrimInsetsFrameLayout.java

Method was deprecated on API 20 but this layout is only used pre kitkat so.
