### ISSUE TITLE
Custom Drawer Layout (Question)

### ISSUE THREAD

**Issue by nowke** [kanytu/android-material-drawer-template#30]
How to customize the drawer layout?

Something like [this](https://github.com/rudsonlive/NavigationDrawer-MaterialDesign)

**Comment by kanytu** [comment]
Just change this file:
https://github.com/kanytu/android-material-drawer-template/blob/master/app/src/main/res/layout/fragment_navigation_drawer.xml

You can customize this xml the way you want your navigation drawer to look like.
