### ISSUE TITLE
Why is selectItem not public?

### ISSUE THREAD

**Issue by surfer190** [kanytu/android-material-drawer-template#32]
```
void selectItem(int position) {
```

Why is this not public?

File: **NavigationDrawerFragment.java**
Line: **147**

**Comment by kanytu** [comment]
For the same reason google uses it as a private method:
{sdk}\tools\templates\activities\NavigationDrawerActivity\root\src\app_package\NavigationDrawerFragment.java.ftl

Line 191:

    private void selectItem(int position) {
        mCurrentSelectedPosition = position;
        if (mDrawerListView != null) {
            mDrawerListView.setItemChecked(position, true);
        }
        if (mDrawerLayout != null) {
            mDrawerLayout.closeDrawer(mFragmentContainerView);
        }
        if (mCallbacks != null) {
            mCallbacks.onNavigationDrawerItemSelected(position);
        }
    }

However, just like any template, feel free to change it to public.
