### ISSUE TITLE
Navigation drawer bottom item

### ISSUE THREAD

**Issue by sameera26** [kanytu/android-material-drawer-template#39]
I have successfully integrated material navigation drawer. My problem is i want to add bottom item in the navigation drawer. Can you guid me to achieve this. Thanks!

**Comment by kanytu** [comment]
For that you need to add the items aligned bottom and make the your navigation drawer list end at the items. Here is an example:


    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                  android:layout_width="match_parent"
                  android:layout_height="match_parent">
    <ListView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@+id/linearLayout"/>

        <LinearLayout
            android:orientation="vertical"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_alignParentLeft="true"
            android:layout_alignParentStart="true"
            android:layout_alignParentBottom="true"
            android:id="@+id/linearLayout">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="New Text"
                android:id="@+id/textView"/>

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="New Text"
                android:id="@+id/textView2"/>
        </LinearLayout>
    </RelativeLayout>

**Comment by sameera26** [comment]
Thanks for the quick response. I added button to the fragment_navigation_drawer.xml and solved my problem. Cheers!

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="240dp"
    android:layout_height="match_parent"
    android:layout_gravity="start"
    >

    <android.support.v7.widget.RecyclerView
        android:id="@+id/drawerList"
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:clickable="true"
        android:focusableInTouchMode="true"
        android:scrollbars="vertical"
        android:focusable="true"
        android:fitsSystemWindows="true"
        android:layout_height="match_parent"
        android:background="@color/myDrawerBackground"/>


    <Button
        android:id="@+id/button2"
        android:layout_height="50dp"
        android:text = "Logout"
        android:layout_width="match_parent"
        android:layout_alignParentBottom="true"/>


</RelativeLayout>
