### ISSUE TITLE
how to move Mainview And Tabhost

### ISSUE THREAD

**Issue by VeeraAndroid** [kanytu/android-material-drawer-template#51]
What I want to do is slide the ActionBar along with the NavigationDrawer when the drawer is opened.
![screen shot 2016-03-14 at 2 39 50 pm](https://cloud.githubusercontent.com/assets/8385761/13741166/c2a4b35a-e9fa-11e5-9c4e-9a2e7871e558.png)

**Comment by kanytu** [comment]
http://stackoverflow.com/a/23954699/3410697
